# This is a basic workflow to help you get started with Actions

name: Check non-task Makefiles

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, reopened, review_requested]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Check Makefiles
        working-directory: tasks/check_makefiles/code
        run: bash check_nontask_makefiles.sh